import "@repo/ui/styles.css";
import type { Metadata } from "next";
import {Navbar} from "../navbar";
import Footer from "../footer";


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
      <div className="flex flex-col">
      <Navbar />
        {children}
        <Footer />
        </div>
  );
}

export default RootLayout;
