export {SectionHero} from "./sectionHero";
export {SectionStats} from "./sectionStats";
export {SectionService} from "./sectionService";
export {SectionAppointment} from "./sectionAppointment";
export {SectionTestimonial} from "./sectionTestimonial";
export {SectionTeam} from "./sectionTeam"
export {SectionFaq} from "./sectionFaq"
export {SectionBanner} from "./sectionBanner";
export {BannerAboutUs} from "./bannerAboutUs"
export {SectionCourseDetail} from "./sectionCourseDetails"